.TH "apt-get" "8" "25 Oct 2000" "apt" "" 
.SH "NAME" 
apt-get \- APT package handling utility -- command-line interface
.PP 
.SH "SYNOPSIS" 
apt-get [options] [command] [package \&.\&.\&.]
.PP 
.SH "DESCRIPTION" 
.PP 
apt-get is the command-line tool for handling packages, and may be considered 
the user\'s "back-end" to apt(8)\&.
.PP 
\fIcommand\fP is one of:
.IP o 
update
.IP o 
upgrade
.IP o 
dselect-upgrade [1]
.IP o 
dist-upgrade
.IP o 
install package1 [package2] [\&.\&.\&.]
.IP o 
remove package1 [package2] [\&.\&.\&.]
.IP o 
source package1 [package2] [\&.\&.\&.]
.IP o 
check
.IP o 
clean
.IP o 
autoclean
.PP 
Unless the -h, or --help option is given one of the above commands
must be present\&.
.PP
Note:
[1] Debian systems only
.PP 
.IP "\fBupdate\fP" 
\fBupdate\fP is used to resynchronize the package overview files from their
sources\&. The overviews of available packages are fetched from the
location(s) specified in \fB/etc/apt/sources\&.list\fP\&.
For example, when using a Debian archive, this command retrieves and
scans the \fBPackages\&.gz\fP files, so that information about new and updated 
packages is available\&. An \fBupdate\fP should always be performed before an
\fBupgrade\fP \fBdist-upgrade\fP\&. Please be aware that the overall progress
meter will be incorrect as the size of the package files cannot be known in
advance\&.
.IP 
.IP "\fBupgrade\fP" 
\fBupgrade\fP is used to install the newest versions of all packages currently 
installed on the system from the sources enumerated in
\fB/etc/apt/sources\&.list\fP\&. Packages currently installed with new versions 
available are retrieved and upgraded; under no circumstances are currently 
installed packages removed, or packages not already installed retrieved and 
installed\&. New versions of currently installed packages that cannot be 
upgraded without changing the install status of another package will be left 
at their current version\&. An \fBupdate\fP must be performed first so that
\fBapt-get\fP knows that new versions of packages are available\&.
.IP 
.IP "\fBdselect-upgrade\fP" 
\fBdselect-upgrade\fP
is used in conjunction with the traditional Debian GNU/Linux packaging
front-end, \fBdselect (8)\fP\&. \fBdselect-upgrade\fP
follows the changes made by \fBdselect\fP to the \fIStatus\fP
field of available packages, and performs the actions necessary to realize
that state (for instance, the removal of old and the installation of new
packages)\&. 
This command is only available on Debian systems.
.IP 
.IP "\fBdist-upgrade\fP" 
\fBdist-upgrade\fP,in addition to performing the function of \fBupgrade\fP,
also intelligently handles changing dependencies with new versions of
packages; \fBapt-get\fP has a "smart" conflict resolution system, and it will 
attempt to upgrade the most important packages at the expense of less 
important ones if necessary\&. The \fB/etc/apt/sources\&.list\fP file contains a 
list of locations from which to retrieve desired package files\&.
.IP 
.IP "\fBinstall\fP" 
\fBinstall\fP is followed by one or more \fIpackages\fP desired for installation\&. 
Each \fIpackage\fP is a package name, not a fully qualified filename 
(for instance, in a Debian GNU/Linux system, \fIldso\fP would be the argument 
provided, not \fIldso_1\&.9\&.6-2\&.deb\fP)\&. All packages required by the package(s) 
specified for installation will also be retrieved and installed\&. The
\fB/etc/apt/sources\&.list\fP file is used to locate the desired packages\&. If a
hyphen is appended to the package name (with no intervening space), the 
identified package will be removed if it is installed\&. This latter feature 
may be used to override decisions made by apt-get\'s conflict resolution system\&.
.IP 
If no package matches the given expression and the expression contains one
of \'\&.\', \'?\' or \'*\' then it is assumed to be a POSIX regex and it is applied
to all package names in the database\&. Any matches are then installed (or
removed)\&. Note that matching is done by substring so \'lo*\' matches \'how-lo\'
and \'lowest\'\&. If this is undesired prefix with a \'^\' character\&.
.IP 
.IP "\fBremove\fP" 
\fBremove\fP is identical to \fBinstall\fP except that packages are removed
instead of installed\&. If a plus sign is appended to the package name (with no
intervening space), the identified package will be installed\&.
.IP 
.IP "\fBsource\fP" 
\fBsource\fP causes apt-get to fetch source packages\&. APT will examine the
available packages to decide which source package to fetch\&. It will then
find and download into the current directory the newest available version of
that source package\&. Source packages are tracked separately from binary
packages via \fBdeb-src\fP or \fBrpm-src\fP type lines in the \fB/etc/apt/sources\&.list\fP file\&.
This probably will mean that you will not get the same source as the package
you have installed or as you could install\&. If the --compile options is
specified then the package will be compiled to a binary \&.deb using
dpkg-buildpackage, or under RPM based systems, it will compile
to a binary \&.rpm using rpm -ba. If --download-only is specified then 
the source package will not be unpacked\&
.IP 
Note that source packages are not tracked like binary packages, they exist
only in the current directory and are similar to downloading source
tar balls\&.
.IP 
.IP "\fBcheck\fP" 
\fBcheck\fP is a diagnostic tool; it updates the package cache and checks for 
broken packages\&.
.IP 
.IP "\fBclean\fP" 
\fBclean\fP clears out the local repository of retrieved package files\&. It 
removes everything but the lock file from \fB/var/cache/apt/archives/\fP
and \fB/var/cache/apt/archives/partial/\fP\&.
When APT is used as a \fBdselect(8)\fP method, \fBclean\fP is run automatically\&.
Those who do not use dselect will likely want to run \f(CWapt-get clean\fP
from time to time to free up disk space\&.
.IP 
.IP "\fBautoclean\fP" 
Like \fBclean\fP, \fBautoclean\fP clears out the local repository of retrieved 
package files\&. The difference is that it only removes package files that
can no longer be downloaded, and are largely useless\&. This allows a
cache to be maintained over a long period without it growing out of
control\&.
.IP 
.PP 
.SH "OPTIONS" 
All command line options may be set using the configuration file, the
descriptions indicate the configuration option to set\&. For boolean
options you can override the config file by using something like \fB-f-\fP,
\fB--no-f\fP, \fB-f=no\fP or several other variations\&.
.PP 
.IP "\fB-d, --download-only\fP" 
Download only; package files are only retrieved, not unpacked or installed\&.
Configuration Item: \fBAPT::Get::Download-Only\fP\&.
.IP 
.IP "\fB-f, --fix-broken\fP" 
Fix; attempt to correct a system with broken dependencies in
place\&. This option, when used with install/remove, can omit any packages
to permit APT to deduce a likely solition\&. Any Package that are specified
must completly correct the problem\&. The option is sometimes necessary when 
running APT for the first time; APT itself does not allow broken package 
dependencies to exist on a system\&. It is possible that a system\'s 
dependency structure can be so corrupt as to require manual intervention 
(which usually means using dselect or dpkg --remove to eliminate some of 
the offending packages)\&. Use of this option together with -m may produce an 
error in some situations\&. Configuration Item: \fBAPT::Get::Fix-Broken\fP\&.
.IP 
.IP "\fB-h, --help\fP" 
Help; display a helpful usage message and exits\&.
.IP 
.IP "\fB-v, --version\fP" 
Show the program version\&.
.IP 
.IP "\fB-m, --ignore-missing, --fix-missing\fP" 
Ignore missing packages; If packages cannot be retrieved or fail the    
integrity check after retrieval (corrupted package files), hold back    
those packages and handle the result\&. Use of this option together with  
-f may produce an error in some situations\&. If a package is selected for 
installation (particularly if it is mentioned on the command line) and it
could not be downloaded then it will be silently held back\&.
Configuration Item: \fBAPT::Get::ignore-missing\fP\&.
.IP
.IP "\fB-S, --summary\fP"
When used with the upgrade or dist-upgrade commands,
displays information of what would be upgraded, with importance
and a summary of changes (when such data is available) and stops.
Configuration Item: \fBAPT::Get::Show-Upgrade-Summary\fP&.
.IP 
.IP "\fB--no-download\fP" 
Disables downloading of packages\&. This is best used with --ignore-missing to
force APT to use only the \&.debs it has already downloaded\&.
Configuration Item: \fBAPT::Get::No-Download\fP\&.
.IP 
.IP "\fB-q, --quiet\fP" 
Quiet; produces output suitable for logging, omitting progress indicators\&.
More q\'s will produce more quiet up to a maximum of 2\&. You can also use
\fB-q=#\fP to set the quiet level, overriding the configuration file\&. Note that
quiet level 2 implies -y, you should never use -qq without a no-action
modifier such as -d, --print-uris or -s as APT may decided to do something
you did not expect\&.
Configuration Item: \fBquiet\fP
.IP 
.IP "\fB-s, --simulate, --just-print, --dry-run, --recon, --no-act\fP" 
No action; perform a simulation of events that would occur but do not
actually change the system\&. Configuration Item: \fBAPT::Get::Simulate\fP\&. 
.IP 
Simulate prints out
a series of lines each one representing a dpkg operation, Configure (Conf),
Remove (Remv), Unpack (Inst)\&. Square brackets indicate broken packages with
and empty set of square brackets meaning breaks that are of no consequence
(rare)\&.
.IP 
.IP "\fB-y, --yes, --assume-yes\fP" 
Automatic yes to prompts; assume "yes" as answer to all prompts and run
non-interactively\&. If an undesirable situation, such as changing a held
package or removing an essential package occurs then \fBapt-get\fP will
abort\&. Configuration Item: \fBAPT::Get::Assume-Yes\fP\&.
.IP 
.IP "\fB-u, --show-upgraded\fP" 
Show upgraded packages; Print out a list of all packages that are to be
upgraded\&. Configuration Item: \fBAPT::Get::Show-Upgraded\fP\&.
.IP 
.IP "\fB-b, --compile, --build\fP" 
Compile source packages after downloading them\&.
Configuration Item: \fBAPT::Get::Compile\fP\&.
.IP 
.IP "\fB--ignore-hold\fP" 
Ignore package Holds; This causes \fBapt-get\fP to ignore a hold placed on 
a package\&. This may be useful in conjunction with \fBdist-upgrade\fP to
override a large number of undesired holds\&. Configuration Item: \fBAPT::Ignore-Hold\fP\&.
.IP 
.IP "\fB--no-upgrade\fP" 
Do not upgrade packages; When used in conjunction with \fBinstall\fP
\fBno-upgrade\fP will prevent packages listed from being upgraded if they
are already installed\&. Configuration Item: \fBAPT::Get::no-upgrade\fP\&.
.IP 
.IP "\fB--force-yes\fP" 
Force yes; This is a dangerous option that will cause apt to continue without
prompting if it is doing something potentially harmful\&. It should not be used
except in very special situations\&. Using \fBforce-yes\fP can potentially destroy
your system! Configuration Item: \fBAPT::Get::force-yes\fP\&.
.IP 
.IP "\fB--print-uris\fP" 
Instead of fetching the files to install their URIs are printed\&. Each
URI will have the path, the destination file name, the size and the expected
md5 hash\&. Note that the file name to write to will not always match
the file name on the remote site! This also works with the \fBsource\fP
command\&. Configuration Item: \fBAPT::Get::Print-URIs\fP\&.
.IP 
.IP "\fB--purge\fP" 
Use purge instead of remove for anything that would be removed\&.
This option has no effect on RPM based systems.
Configuration Item: \fBAPT::Get::Purge\fP\&.
.IP 
.IP "\fB--reinstall\fP" 
Re-Install packages that are already installed and at the newest version\&.
.IP 
.IP "\fB--list-cleanup\fP" 
This option defaults to on, use \fB--no-list-cleanup\fP to turn it off\&.
When on apt-get will automatically manage the contents of 
/var/state/apt/lists to ensure that obsolete files are erased\&. The only 
reason to turn it off is if you frequently change your source list\&. 
Configuration Item: \fBAPT::Get::List-Cleanup\fP
.IP 
.IP "\fB--trivial-only\fP" 
Only perform operations are \'trivial\'\&. Logically this can be considered
related to --assume-yes, where --assume-yes will answer yes to any prompt,
--trivial-only will answer no\&. Configuration Item: \fBAPT::Get::Trivial-Only\fP
.IP 
.IP "\fB--no-remove\fP" 
If any packages are to be removed apt-get immediately aborts without
prompting\&. Configuration Item: \fBAPT::Get::No-Remove\fP
.IP 
.IP "\fB--diff-only\fP, \fB--tar-only\fP" 
Download only the diff or tar file of a source archive\&. 
Configuration Item: \fBAPT::Get::Diff-Only\fP
.IP 
.IP "\fB-c, --config-file\fP" 
Configuration File; Specify a configuration file to use\&. \fBapt-get\fP will
read the default configuration file and then this configuration file\&. See
\fBapt\&.conf(5)\fP for syntax information\&.
.IP 
.IP "\fB-o, --option\fP" 
Set a Configuration Option; This will set an arbitrary configuration option\&.
The syntax is 

.nf 
 
-o Foo::Bar=bar
.fi 
 

.PP 
.SH "FILES" 
.IP o 
/etc/apt/sources\&.list 
locations to fetch packages from
.IP 
.IP o 
/var/cache/apt/archives/
storage area for retrieved package files
.IP 
.IP o 
/var/cache/apt/archives/partial/
storage area for package files in transit
.IP 
.IP o 
/var/state/apt/lists/
storage area for state information for each package resource specified in
the source list
.IP 
.IP o 
/var/state/apt/lists/partial/
storage area for state information in transit
.PP 
.SH "SEE ALSO" 
apt-cache(8),
dpkg(8),
dselect(8),
sources\&.list(5),
apt\&.conf(5),
The APT Users Guide in /usr/doc/apt/
.PP 
.SH "DIAGNOSTICS" 
apt-get returns zero on normal operation, decimal 100 on error\&.
.PP 
.SH "BUGS" 
See http://bugs\&.debian\&.org/apt\&.  If you wish to report a
bug in \fBapt-get\fP, please see \fB/usr/doc/debian/bug-reporting\&.txt\fP
or the \fBbug(1)\fP command\&. If you are using apt on a RPM based
system, please use http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTHOR" 
apt-get was written by the APT team <apt@packages\&.debian\&.org>
and ported to RPM based systems by Conectiva S.A. 
<kojima@conectiva\&.com\&.br>\&.
