.TH "apt-cdrom" "8" "25 Oct 2000" "apt" "" 
.SH "NAME" 
apt-cdrom \- APT CDROM managment utility
.PP 
.SH "SYNOPSIS" 
apt-cdrom command
.PP 
.SH "DESCRIPTION" 
\fBapt-cdrom\fP is used to add a new CDROM to APTs list of available sources\&.
\fBapt-cdrom\fP takes care of determining the structure of the disc as well
as correcting for several possible mis-burns and verifying the index files\&.
It is necessary to use \fBapt-cdrom\fP to add CDs to the APT system, it cannot
be done by hand\&. Furthermore each disk in a multi-cd set must be inserted
and scanned seperately to account for possible mis-burns\&.
.PP 
\fIcommand\fP is one of:
.IP o 
add 
.PP 
Unless the -h, or --help option is given one of the above commands
must be present\&.
.PP 
.IP "\fBadd\fP" 
\fBadd\fP is used to add a new disc to the source list\&. It will unmount the
CDROM device, prompt for a disk to be inserted and then procceed to scan it
and copy the index files\&. If the disc does not have a proper \fB\&.disk/\fP 
directory you will be prompted for a descriptive title\&.
.IP 
APT uses a CDROM ID to track which disc is currently in the drive and
maintains a database of these IDs in \fB/var/state/apt/cdroms\&.list\fP
.IP 
.PP 
.SH "OPTIONS" 
All command line options may be set using the configuration file, the
descriptions indicate the configuration option to set\&. For boolean
options you can override the config file by using something like \fB-f-\fP,
\fB--no-f\fP, \fB-f=no\fP or several other variations\&.
.PP 
.IP "\fB-h, --help\fP" 
Show a short usage summary\&.
.IP 
.IP "\fB-v, --version\fP" 
Show the program verison\&.
.IP 
.IP "\fB-d --cdrom\fP" 
Mount point; specify the location to mount the cdrom\&. This mount point must
be listed in \fB/etc/fstab\fP and propely configured\&. 
Configuration Item: \fBAcquire::cdrom::mount\fP\&.
.IP 
.IP "\fB-r --rename\fP" 
Rename a disc; change the label of a disk or override the disks given label\&.
This option will cause \fBapt-cdrom\fP to prompt for a new label
Configuration Item: \fBAPT::CDROM::Rename\fP\&.
.IP 
.IP "\fB-m, --no-mount\fP" 
No mounting; prevent \fBapt-cdrom\fP from mounting and unmounting the mount
point\&.
Configuration Item: \fBAPT::CDROM::NoMount\fP\&.
.IP 
.IP "\fB-f, --fast\fP" 
Fast Copy; Assume the package files are valid and do not check every package\&.
This option should be used only if \fBapt-cdrom\fP has been run on this disc
before and did not detect any errors\&.
Configuration Item: \fBAPT::CDROM::Fast\fP\&.
.IP 
.IP "\fB-a, --thorough\fP" 
Thorough Package Scan; This option may be needed with some old Debian 1\&.1/1\&.2
burns that have Package files in strange places\&. It takes much longer to
scan the CD but will pick them all up\&.
.IP 
.IP "\fB-n --just-print, --recon, --no-act\fP" 
No Changes; Do not change the sources\&.list and do not write package files\&. 
Everything is still checked however\&.
Configuration Item: \fBAPT::CDROM::NoAct\fP\&.
.IP 
.IP "\fB-c, --config-file\fP" 
Configuration File; Specify a configuration file to use\&. \fBapt-get\fP will
read the default configuration file and then this configuration file\&. See
\fBapt\&.conf(5)\fP for syntax information\&.
.IP 
.IP "\fB-o, --option\fP" 
Set a Configuration Option; This will set an arbitary configuration option\&.
The syntax is 

.nf 
 
-o Foo::Bar=bar
.fi 
 

.PP 
.SH "FILES" 
.IP o 
/etc/apt/sources\&.list 
locations to fetch packages from
.IP 
.IP o 
/var/state/apt/lists/
storage area for state information for each package resource specified in
.IP 
.IP o 
/var/state/apt/lists/partial/
storage area for state information in transit
.IP 
.IP o 
/var/state/apt/cdroms\&.list
list of cdrom IDs and names\&.
.PP 
.SH "SEE ALSO" 
apt-get(8),
sources\&.list(5),
apt\&.conf(5)
.PP 
.SH "DIAGNOSTICS" 
apt-cdrom returns zero on normal operation, decimal 100 on error\&.
.PP 
.SH "BUGS" 
See http://bugs\&.debian\&.org/apt\&.  If you wish to report a
bug in \fBapt-cache\fP, please see \fB/usr/doc/debian/bug-reporting\&.txt\fP
or the \fBbug(1)\fP command\&.  If you are using apt on a RPM based
system, please use http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTHOR" 
apt-get was written by the APT team <apt@packages\&.debian\&.org>
and ported to RPM based systems by Conectiva S.A. 
<kojima@conectiva\&.com\&.br>\&.

