.TH "apt-cache" "8" "25 Oct 2000" "apt" "" 
.SH "NAME" 
apt-cache \- APT package handling utility -- cache manipulator
.PP 
.SH "SYNOPSIS" 
apt-cache command [argument \&.\&.\&.]
.PP 
.SH "DESCRIPTION" 
\fBapt-cache\fP performs a variety of operations on APT\'s package cache\&.
\fBapt-cache\fP is seldom called directly; instead its operations are
performed automatically by the other \fBapt\fP utilities\&.
.PP 
\fIcommand\fP is one of:
.IP o 
add file1 [file2] [\&.\&.\&.]
.IP o 
gencaches
.IP o 
showpkg package1 [package2] [\&.\&.\&.]
.IP o 
stats
.IP o 
dump
.IP o 
dumpavail
.IP o 
unmet
.IP o 
check
.IP o 
search
.IP o 
show
.IP o 
showpkg
.IP o 
depends
.IP o 
pkgnames
.IP o 
dotty
.PP 
Unless the -h, or --help option is given one of the above commands
must be present\&.
.PP 
.IP "\fBadd\fP" 
\fBadd\fP adds the names package index files to the package cache\&.
.IP 
.IP "\fBgencaches\fP" 
\fBgencaches\fP performs the same opration as \fBapt-get check\fP\&. It builds
the source and package caches from thes sources in \fB/etc/apt/sources\&.list\fP
and from \fB/var/lib/dpkg/status\fP (or the RPM database)\&.
.IP 
.IP "\fBshowpkg\fP" 
\fBshowpkg\fP displays information about the packages listed on the 
command line\&. Remaining arguments are package names\&. The available versions 
and reverse dependencies of each package listed are listed, as well as      
forward dependencies for each version\&. Forward (normal) dependencies   
are those packages upon which the package in question depends; reverse  
dependencies are those packages that depend upon the package in         
question\&. Thus, forward dependencies must be satisfied for a package,  
but reverse dependencies need not be\&.
For instance, \fBapt-cache showpkg libreadline2\fP would produce output similar
to the following:
.IP 

.nf 
 

Package: libreadline2

Versions:

2\&.1-12(/var/state/apt/lists/debian\&.midco\&.net_debian_dists_slink_main_binary-i386_Packages),

Reverse Depends: 

  libreadlineg2,libreadline2

  libreadline2-altdev,libreadline2
Dependencies:

2\&.1-12 - libc5 (2 5\&.4\&.0-0) ncurses3\&.0 (0 (null)) ldso (2 1\&.9\&.0-1)

Provides: 

2\&.1-12 - 

Reverse Provides: 

.fi 
 
			    
.IP 
Thus it may be seen that libreadline2, version 2\&.1-8, depends on libc5,
ncurses3\&.0, and ldso, which must be installed for libreadline2 to work\&. In
turn, libreadlineg2 and libreadline2-altdev depend on libreadline2\&. If
libreadline2 is installed, libc5, ncurses3\&.0, and ldso must also be
installed; libreadlineg2 and libreadline2-altdev do not have to be
installed\&. For the specific meaning of the remainder of the output it
is best to consult the apt source code\&.
.IP 
.IP "\fBstats\fP" 
\fBstats\fP displays some statistics about \fBcache\fP\&.
No further arguments are expected\&. Statistics reported are:
.IP o 
\fBTotal package names\fP is the number of package names found in the cache\&.
.IP 
.IP o 
\fBNormal packages\fP is the number of regular, ordinary package names; these
are packages that bear a one-to-one correspondence between their names and
the names used by other packages for them in dependencies\&. The majority of
packages fall into this category\&.
.IP 
.IP o 
\fBPure virtual packages\fP is the number of packages that exist only as 
a virtual package name; that is, packages only "provide" the virtual 
package name, and no package actually uses the name\&. For instance, 
"mail-transport-agent" in the Debian GNU/Linux system is a pure virtual 
package; several packages provide "mail-transport-agent", but there is no 
package named "mail-transport-agent"\&.
.IP 
.IP o 
\fBSingle virtual packages\fP is the number of packages with only one 
package providing a particular virtual package\&. For example, in the 
Debian GNU/Linux system, "X11-text-viewer" is a virtual package, but only 
one package, xless, provides "X11-text-viewer"\&.
.IP 
.IP o 
\fBMixed virtual packages\fP is the number of packages that either provide 
a particular virtual package or have the virtual package name as the 
package name\&. For instance, in the Debian GNU/Linux system, e2fsprogs is 
both an actual package, and provided by the e2compr package\&.
.IP 
.IP o 
\fBMissing\fP is the number of package names that were referenced in a 
dependency but were not provided by any package\&. Missing packages may be 
in evidence if a full distribution is not accesssed, or if a package 
(real or virtual) has been dropped from the distribution\&.
.IP 
.IP o 
\fBTotal distinct\fP versions is the number of package versions found in 
the cache; this value is therefore at least equal to the number of total 
package names\&. If more than one distribution (both "stable" and "unstable", 
for instance), is being accessed, this value can be considerably larger 
than the number of total package names\&.
.IP 
.IP o 
\fBTotal dependencies\fP is the number of dependency relationships claimed 
by all of the packages in the cache\&.
.IP 
.IP "\fBdump\fP" 
\fBdump\fP shows a short listing of every package in the cache\&. It is primarily
for debugging\&.
.IP 
.IP "\fBdumpavail\fP" 
\fBdumpavail\fP prints out an available list to stdout\&. This is suitable for use
with \fBdpkg\fP and is used by the \fBdselect\fP method\&.
.IP 
.IP "\fBunmet\fP" 
\fBunmet\fP displays a summary of all unmet dependencies in the package cache\&.
.IP 
.IP "\fBcheck\fP" 
\fBcheck\fP is a random function for testing certain aspects of the cache\&.
Do not use it\&.
.IP 
.IP "\fBshowpkg\fP" 
\fBshowpkg\fP displays a listing of the given package cache structure and some
related information about it\&. The list is meant primarily for debugging\&.
.IP 
.IP "\fBshow\fP" 
\fBshow\fP performs a function similar to dpkg --print-avail or rpm -qi,
it displays the package records for the named packages\&.
.IP 
.IP "\fBsearch\fP" 
\fBsearch\fP performs a full text search on all available package files for
the pattern given\&. It searchs the package names and the descriptions for
an occurance of the string and prints out the package name and the short
description\&. If --full is given then output identical to \fBshow\fP is produced
for each matched package and if --names-only is given then the long
description is not searched, only the package name is\&.
.IP 
.IP "\fBdepends\fP" 
\fBdepends\fP shows a listing of each dependency a package has and all
the possible other packages that can fullfill that dependency\&.
.IP 
.IP "\fBpkgnames\fP" 
This command prints the name of each package in the system\&. The optional
argument is a prefix match to filter the name list\&. The output is suitable
for use in a shell tab complete function and the output is generated extremly
quickly\&. This command is best used with the \fB--no-generate\fP option\&.
.IP 
.IP "\fBdotty\fP" 
\fBdotty\fP Takes a list of packages on the command line and gernerates output
suitable for use by dotty from the GraphVis
(http://www\&.research\&.att\&.com/sw/tools/graphviz/) package\&. The result will be
a set of nodes and edges representing the relationships between the
packages\&. By default the given packages will trace out all dependent packages
which can produce a very large graph\&. This can be turned off by setting the 
APT::Cache::GivenOnly option\&.
.IP 
The resulting nodes will have several shapse, normal packages are boxes,
pure provides are triangles, mixed provides are diamonds, 
hexagons are missing packages\&. Orange boxes mean recursion was stopped 
[leaf packages], blue lines are prre-depends, green lines are conflicts\&.
.IP 
Caution, dotty cannot graph larger sets of packages\&.
.IP 
.PP 
.SH "OPTIONS" 
All command line options may be set using the configuration file, the
descriptions indicate the configuration option to set\&. For boolean
options you can override the config file by using something like \fB-f-\fP,
\fB--no-f\fP, \fB-f=no\fP or several other variations\&.
.PP 
.IP "\fB-h, --help\fP" 
Show a short usage summary\&.
.IP 
.IP "\fB-v, --version\fP" 
Show the program verison\&.
.IP 
.IP "\fB-p --pkg-cache\fP" 
Select the file to store the package cache\&. The package cache is the primary
cache used by all operations\&.
Configuration Item: \fBDir::Cache::pkgcache\fP\&.
.IP 
.IP "\fB-s --src-cache\fP" 
Select the file to store the source cache\&. The source is used only by
\fBgencaches\fP and it stores a parsed version of the package information from
remote sources\&. When building the package cache the source cache is used
to advoid reparsing all of the package files\&.
Configuration Item: \fBDir::Cache::srcpkgcache\fP\&.
.IP 
.IP "\fB-q, --quiet\fP" 
Quiet; produces output suitable for logging, omitting progress indicators\&.
More qs will produce more quite up to a maximum of 2\&. You can also use
\fB-q=#\fP to set the quiet level, overriding the configuration file\&.
Configuration Item: \fBquiet\fP\&.
.IP 
.IP "\fB-i --important\fP" 
Print only important deps; for use with unmet causes only \fIDepends\fP and 
\fIPre-Depends\fP relations to be printed\&.
Configuration Item: \fBAPT::Cache::Important\fP\&.
.IP 
.IP "\fB-f --full\fP" 
Print full package records when searching\&. Configuration Item: \fBAPT::Cache::ShowFull\fP\&.
.IP 
.IP "\fB-a --all-versions\fP" 
Print full records for all available versions, this is only applicable to the
show command\&. Configuration Item: \fBAPT::Cache::AllVersions\fP
.IP 
.IP "\fB-g --no-generate\fP" 
Do not perform automatic package cache regeneration, use the cache as it is\&.
Configuration Item: \fBAPT::Cache::NoGenerate\fP\&.
.IP 
.IP "\fB--names-only\fP" 
Only search on the package names, not the long description\&. 
Configuration Item: \fBAPT::Cache::NamesOnly\fP\&.
.IP 
.IP "\fB--all-names\fP" 
Make \fBpkgnames\fP print all names, including virtual packages and missing
dependencies\&. Configuration Item: \fBAPT::Cache::AllNames\fP\&.
.IP 
.IP "\fB-c, --config-file\fP" 
Configuration File; Specify a configuration file to use\&. \fBapt-get\fP will
read the default configuration file and then this configuration file\&. See
\fBapt\&.conf(5)\fP for syntax information\&.
.IP 
.IP "\fB-o, --option\fP" 
Set a Configuration Option; This will set an arbitary configuration option\&.
The syntax is 

.nf 
 
-o Foo::Bar=bar
.fi 
 

.PP 
.SH "FILES" 
.IP o 
/etc/apt/sources\&.list 
locations to fetch packages from
.IP 
.IP o 
/var/state/apt/lists/
storage area for state information for each package resource specified in
.IP 
.IP o 
/var/state/apt/lists/partial/
storage area for state information in transit
.PP 
.SH "SEE ALSO" 
apt-get(8),
sources\&.list(5),
apt\&.conf(5)
.PP 
.SH "DIAGNOSTICS" 
apt-cache returns zero on normal operation, decimal 100 on error\&.
.PP 
.SH "BUGS" 
See http://bugs\&.debian\&.org/apt\&.  If you wish to report a
bug in \fBapt-cache\fP, please see \fB/usr/doc/debian/bug-reporting\&.txt\fP
or the \fBbug(1)\fP command\&. If you are using apt on a RPM based
system, please use http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTHOR" 
apt-get was written by the APT team <apt@packages\&.debian\&.org>
and ported to RPM based systems by 
Alfredo K. Kojima, Conectiva S.A. <kojima@conectiva\&.com\&.br>\&.

