.TH "apt-config" "8" "25 Out 2000" "apt" "" 
.SH "NOME" 
apt-config \- programa APT Configuration Query
.PP 
.SH "SINOPSE" 
apt-config comando
.PP 
.SH "DESCRIÇÃO" 
\fBapt-config\fP é um programa interno usado por várias partes da
suíte APT para fornecer configurabilidade consistente\&. Ele acessa o
arquivo principal de configuração /etc/apt/apt\&.conf de uma forma que
seja fácil de ser usado por aplicações em script\&.
.PP 
\fIcomando\fP é um dos seguintes:
.IP o 
shell
.IP o 
dump
.PP 
A menos que as opções -h ou --help sejam fornecidas, um dos comandos
acima precisa estar presente\&.
.PP 
.IP "\fBshell\fP" 
\fBshell\fP é usado para acessar as informações de configuração de um
script shell\&.
São fornecidos pares de argumentos, o primeiro sendo uma variável
shell e o segundo o valor de configuração a ser questionado\&. Como
saída ele lista uma série de comandos shell de atribuição para cada
valor presente\&. Em um script shell ele seria usado como:
.IP 

.nf 
 

OPTS="-f"

RES=`apt-config shell OPTS MeuApp::Opções`

eval $RES

.fi 
 

.IP 
Isto irá configurar a variável shell de ambiente $OPTS ao valor de
MeuApp::Opções com um padrão de -f\&.
.IP 
Se o ítem de configuração a ser resgatado tiver uma / como prefixo,
ele será resgatado através do modo de nome de arquivo que insere
caminhos base no início\&.
.IP 
.IP "\fBdump\fP" 
Mostra somente o conteúdo do espaço de configuração\&.
.IP 
.PP 
.SH "OPÇÕES" 
Todas as opções de linha de comando podem ser definidas através do
arquivo de configuração; as descrições indicam a opção de configuração
a ser usada\&. Para opções booleanas você pode ignorar o arquivo de
configuração usando algo como \fB-f-\fP, \fB--no-f\fP, \fB-f=no\fP ou
muitas outras variações\&.
.PP 
.IP "\fB-h, --help\fP" 
Mostra um pequeno resumo de utilização\&.
.IP 
.IP "\fB-v, --version\fP" 
Mostra a versão de programa\&.
.IP 
.IP "\fB-c, --config-file\fP" 
Arquivo de Configuração; Especifique um arquivo de configuração a ser
usado\&. \fBapt-get\fP irá ler o arquivo padrão de configuração e
então este arquivo de configuração\&. Consulte \fBapt\&.conf(5)\fP
para informações sobre a sintaxe\&.
.IP 
.IP "\fB-o, --option\fP" 
Define uma Opção de Configuração; Isto irá configurar uma opção
arbitrária de configuração\&.
A sintaxe é 

.nf 
 
-o Foo::Bar=bar
.fi 
 

.PP 
.SH "VEJA TAMBÉM" 
apt\&.conf(5)
.PP 
.SH "DIAGNÓSTICOS" 
apt-config retorna zero em operação normal, 100 decimal 100 quando há erro\&.
.PP 
.SH "ERROS" 
Veja http://bugs\&.debian\&.org/apt\&.  Se você deseja reportar um
erro no \fBapt-config\fP, por favor consulte
\fB/usr/doc/debian/bug-reporting\&.txt\fP ou o comando \fBbug(1)\fP
\&. Se você está usando apt em um sistema baseado em RPM, por favor
use http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTOR" 
apt-get foi escrito pelo time APT <apt@packages\&.debian\&.org> e
portado a sistemas RPM pela Conectiva
S.A. <kojima@conectiva\&.com\&.br>\&.
