.TH "apt\&.conf" "5" "01 Nov 2000" "apt" "" 
.SH "NOME" 
apt\&.conf \- arquivo de configuração do APT
.PP 
.SH "DESCRIÇÃO" 
\fBapt\&.conf\fP é o principal arquivo de configuração da suíte de
ferramentas APT, todas as ferramentas fazem uso do arquivo de
configuração e de um verificador comum de linha de comando para
fornecer um ambiente uniforme\&. Quando uma ferramenta APT é iniciada,
ela irá ler \fB/etc/apt/apt\&.conf\fP, e então ler a configuração
especificada pela variável de ambiente \fB$APT_CONFIG\fP e,
finalmente, irá aplicar as opções de linha de comando (as quais têm
prioridade sobre as diretivas de configuração), possivelmente
carregando mais arquivos de configuração\&.
.PP 
O arquivo de configuração é estruturado em uma árvore com opções
organizadas em grupos funcionais\&. Especificação de opção é fornecida
com uma notação de dois pontos duplos, por exemplo
\fIAPT::Get::Assume-Yes\fP é uma opção na qual o grupo de ferramentas
APT, para a ferramenta Get\&. Opções são herdadas de seus grupos pai\&.
.PP 
Sintaticamente, a linguagem de configuração é modelada conforme as
ferramentas ISC, como bind e dhcp usam\&. Cada linha é na forma
.RS 
APT::Get::Assume-Yes "true";
.RE 
O ponto-e-vírgula final é necessário e as aspas são opcionais\&. Um
novo \fIescopo\fP pode ser aberto com chaves, como:: 

.nf 
 
APT {
  Get {
    Assume-Yes "true";
    Fix-Broken "true";
  };
};

.fi 
 

com retornos de carro colocados para torná-lo mais legível\&. Listas
podem ser criadas abrindo-se um escopo e incluindo uma palavra simples
encapsulada em aspas seguida por um ponto-e-vírgula\&. 
Geralmente o arquivo exemplo de configuração em
\fI/usr/doc/apt/examples/apt\&.conf\fP e \fI/usr/doc/apt/examples/configure-index\fP 
(ou \fI/usr/share/doc/apt*/examples/configure-index\fP no Conectiva) é
um bom guia sobre como o arquivo deve ficar.
.PP 
Todas as ferramentas APT usam uma opção -o que permite que uma
diretiva arbitrária de configuração seja especificada na linha de
comando\&. A sintaxe é um nome completo de opção (APT::Get::Assume-Yes
por exemplo) seguido por um sinal de igual e o novo valor da
opção\&. Listas podem também ser anexadas através da adição de :: no
final do nome da lista.\&.
.PP 
.SH "O Grupo APT" 
Este grupo de opções controla o comportamento geral do APT e também
mantém as opções para todas as ferramentas\&.
.PP 
.IP "\fBArchitecture\fP" 
Arquitetura do Sistema; define a arquitetura a ser usada quando da
busca de arquivos e verificação das listas de pacotes\&. O padrão
interno é a arquitetura para a qual o apt foi compilado\&.
.IP 
.IP "\fBIgnore-Hold\fP" 
Ignora pacotes retidos; Esta opção global faz com que o resolvedor de
problemas ignore pacotes retidos quando da tomada de decisões\&. 
.IP 
.IP "\fBClean-Installed\fP" 
O padrão é ligado (on)\&. Quando ligada, a característica de
auto-limpeza irá remover qualquer pacote o qual não possa ser mais
baixado do cache\&. Quando desligado, pacotes instalados localmente
também são excluídos da limpeza - mas observe que APT não fornece
meios diretos de reinstalá-los.\&.
.IP 
.IP "\fBImmediate-Configure\fP" 
Desabilita Configuração Imediata; Esta perigosa opção desabilita
alguns códigos de ordens do APT para fazê-lo executar algumas poucas
chamadas dpkg\&. Fazer isso pode ser necessário em alguns sistemas
monousuário extremamente lentos mas é muito perigoso e pode fazer com
que os scripts de instalação de pacotes não funcionem, ou pior que isso\&.
Use por sua conta e risco\&. Esta opção não tem nenhum efeito em
sistemas baseados em RPM\&.
.IP 
.IP "\fBForce-LoopBreak\fP" 
Nunca habilite esta opção a menos que você -realmente- saiba o que
está fazendo\&. Ela permite que o APT remova temporariamente um pacote
essencial para quebrar loops Conflitos/Conflitos ou
Conflitos/Pré-dependências entre dois pacotes essenciais\&. TAIS LOOPS
NÃO DEVERIAM EXISTIR E SÃO ERROS GRAVES\&. Esta opção irá funcionar se
os pacotes essenciais não forem tar, gzip, libc, dpkg, bash ou
qualquer coisa que estes pacotes dependam\&.
.IP 
.IP "\fBCache-Limit\fP" 
APT usa arquivo de cache de tamanho fixo mapeando a memória que
armazena as informações  \'disponíveis\'\&. Isto define o tamanho
desse cache\&.
.IP 
.IP "\fBGet\fP" 
A subseção Get controla a ferramenta \fBapt-get(8)\fP, por favor
consulte sua documentação para mais informações sobre as opções aqui\&.
.IP 
.IP "\fBCache\fP" 
A subseção Cache controla a ferramenta \fBapt-cache(8)\fP, por favor
consulte sua documentação para mais informações sobre estas opções\&.
.IP 
.IP "\fBCDROM\fP" 
A subseção CDROM controla a ferramenta \fBapt-cdrom(8)\fP, por favor
consulte sua documentação para mais informações sobre estas opções\&.
.IP 
.PP 
.SH "O Grupo Acquire" 
O grupo de opções \fBAcquire\fP controla o download de pacotes e de
tratadores URI\&. 
.PP 
.IP "\fBQueue-Mode\fP" 
Modo de fila; \fBQueue-Mode\fP pode ser um dos \fBhost\fP ou
\fBaccess\fP o que determina como APT paraleliza conexões
externas\&. \fBhost\fP significa que uma conexão por máquina alvo pode
ser aberta, \fBaccess\fP significa que uma conexão por tipo URI pode
ser aberta\&.
.IP 
.IP "\fBRetries\fP" 
Número de tentativas a executar\&. Se for diferente de zero, apt irá
tentar buscar por arquivos que falharam pelo número fornecido de vezes\&.
.IP 
.IP "\fBSource-Symlinks\fP" 
Usar links simbólicos para arquivos fonte\&. Se configurado para
"true" então os arquivos fonte serão simbolicamente linkados quando
possível, em vez de serem copiados\&. "True" é o padrão
.IP 
.IP "\fBhttp\fP" 
HTTP URIs; http::Proxy é o proxy http padrão a ser usado\&. Ele está
na forma padrão de
\fIhttp://[[usuário][:pass]@]máquina[:porta]/\fP\&. Proxies para
máquinas também podem ser especificados através da forma
http::Proxy::<máquina> com a palavra-chave especial \fIDIRECT\fP
significando o não uso de proxies\&. A variável de ambiente
\fI$http_proxy\fP sobrepõe todas as configurações\&.
.IP 
Três configurações são fornecidas para controle de cache com caches de
proxy que estejam de acordo com o padrão HTTP/1\&.1\&. \fBNo-Cache\fP
diz ao proxy para não usar sua resposta sob cache em algumas
circunstâncias, \fBMax-Age\fP é enviada apenas para arquivos de índice
e diz ao cache para atualizar seu objeto caso seja mais antigo que o
número fornecido de segundos\&. 
Debian atualiza seus arquivos de índice diariamente, de forma que o
padrão é 1 dia\&. \fBNo-Store\fP especifica que o cache não deve nunca
armazenar este pedidom ele é apenas definido para arquivos
comuns\&. Isto pode ser útil para evitar a poluição de um cache de
proxy com arquivos \&.deb muito longos\&. Nota: Squid 2\&.0\&.2 não
suporta nenhuma destas opções\&. 
.IP 
A opção \fBtimeout\fP configura o temporizador de tempo limite usado
pelo método, isto se aplica a todas as coisas, incluindo o tempo
limite de conexão e o tempo limite de dados\&.
.IP 
Uma configuração é fornecida para controlar a profundidade do pipeline
em casos onde o servidor remoto não está de acordo com RFC ou tem
erros (como o Squid 2\&.0\&.2)
Acquire::http::Pipeline-Depth pode ser um valor de 0 a 5, indicando o
número de pedidos que APT deve enviar\&.
.IP 
.IP "\fBftp\fP" 
URis FTP; ftp::Proxy é o servidor proxy padrão a ser usado\&. Ele está
na forma padrão de \fIftp://[[usuário][:pass]@]máquina[:porta]/\fP e é
sobreposto pela variável de ambiente ftp_proxy\&. Para usar um proxy
ftp você deverá configurar o script ftp::ProxyLogin no arquivo de
configuração\&. Esta entrada especifica os comandos a serem enviados
para dizer ao servidor proxy o que deve ser conectado aonde\&. Por
favor consulte \fI/usr/doc/apt/examples/configure-index\fP para um
exemplo de como fazer isso\&. As variáveis de substituição disponíveis
são $(PROXY_USER), $(PROXY_PASS), $(SITE_USER), $(SITE_PASS), $(SITE),
e $(SITE_PORT)\&. 
Cada uma é obtida de seu respectivo componente URI\&.
.IP 
A opção \fBtimeout\fP define o temporizador de tempo limite a ser
utilizado pelo método, isto se aplica a todas as coisas, incluindo
tempo limite de conexão e tempo limite de dados\&.
.IP 
Muitas configurações são fornecidas para controlar o modo
passivo\&. Geralmente é seguro deixar o modo passivo ligado (on), ele
funciona em quase todos os ambientes\&. Entretanto, algumas situações
necessitam do modo passivo desligado, e o modo ftp de porta usado em
seu lugar\&. Isto pode ser executado globalmente, para conexões que
passam por um proxy ou por uma máquina específica (Consulte o arquivo
exemplo de configuração para exemplos)
.IP 
É possível executar proxy FTP sobre HTTP configurando a variável de
ambiente \fIftp_proxy\fP para uma url http - consulte a discussão do
método http acima para informações na sintaxe\&. Você não pode
definir isto no arquivo de configuração e não é recomendável usar FTP
sobre HTTP devido a sua baixa eficiência\&.
.IP 
.IP "\fBcdrom\fP" 
URIs CDROM; a única configuração para URIs CDROM é o ponto de
montagem, cdrom::Mount, o qual precisa ser o ponto de montagem do
drive de CDROM conforme especificado em /etc/fstab\&.
É possível fornecer comandos alternativos de montagem e desmontagem
caso o seu ponto de montagem não possa ser listado no fstab (como uma
montagem SMB)\&. A sintaxe é colocar "/cdrom/"::Mount "foo"; dentro do
bloco cdrom\&. É importante manter a barra no final\&. Comandos de
desmontagem podem ser especificados através de UMount\&.
.IP 
.PP 
.SH "Diretórios" 
A seção \fBDir::State\fP tem diretórios pertinentes a informações do
estado local\&. \fBlists\fP é o diretório onde devem ser colocadas
listas de pacotes e \fBstatus\fP é o nome do arquivo de status
dpkg\&. \fBDir::State\fP contém o diretório padrão que entrará como
prefixo em todos os sub-itens, caso eles não se iniciem com \fI/\fP ou
\fI\&./\fP\&. \fBxstatus\fP e \fBuserstatus\fP são para uso futuro\&.
.PP 
\fBDir::Cache\fP contém posições pertinentes a informações sobre o cache local, como os caches de dois pacotes \fBsrcpkgcache\fP e \fBpkgcache\fP bem como a posição onde devem ser colocados arquivos baixados, \fBDir::Cache::archives\fP\&. Como \fBDir::State\fP o diretório padrão é contido em \fBDir::Cache\fP
.PP 
\fBDir::Etc\fP contém a localização dos arquivos de configuração, \fBsourcelist\fP fornece a localização da lista de fontes e \fBmain\fP é o arquivo padrão de configuração (configuração sem efeito)
.PP 
Programas binários são apontados por \fBDir::Bin\fP\&. \fBmethods\fP especifica a localização dos tratadores de métodos e \fBgzip\fP, \fBdpkg\fP, \fBrpm\fP, \fBapt-get\fP, \fBdpkg-source\fP, \fBdpkg-buildpackage\fP e \fBapt-cache\fP especificam a localização dos respectivos programas\&.
.PP 
.SH "APT em DSelect" 
Quando APT é usado como um método \fBdselect(8)\fP, muitas diretivas de configuração controlam o comportamento padrão\&. Elas estão na seção \fBDSelect\fP\&.
.PP 
.IP "\fBClean\fP" 
Modo de cache limpo; este valor pode ser um entre always, auto, prompt e never\&.
always irá remover todos os arquivos após eles serem baixados; auto apenas removerá coisas que não podem mais ser baixadas (substituídas por uma nova versão, por exemplo)
.IP 
.IP "\fBOptions\fP" 
O conteúdo desta variável é passado ao \fBapt-get(8)\fP como opções de linha de comando durante a execução na fase de instalação\&.
.IP 
.IP "\fBUpdateOptions\fP" 
O conteúdo desta variável é passado ao \fBapt-get(8)\fP como opções de linha de comando durante a execução na fase de atualização\&.
.IP 
.IP "\fBPromptAfterUpdate\fP" 
Se for "true", a operação de Atualização ([U]pdate) no dselect sempre irá pedir para continuar\&. 
O padrão é pedir apenas quando houver erros\&.
.PP 
.SH "How APT calls DPkg" 
Muitas diretivas de configuração controlam como o APT chama dpkg\&. Elas estão na seção \fBDPkg\fP\&.
.PP 
.IP "\fBOptions\fP" 
Esta é uma lista de opções a serem passadas ao dpkg\&. As opções precisam ser especificadas através na notação de lista e cada item da lista deve ser passado como um argumento simples ao dpkg\&.
.IP 
.IP "\fBPre-Invoke\fP, \fBPost-Invoke\fP" 
Esta é uma lista de comandos shell a serem executados antes/depois de chamar dpkg\&. Como \fBOptions\fP isto deve ser especificado na notação lista\&. Os comandos são chamados em ordem usando /bin/sh; em caso de falhas a execução do APT é cancelada\&.
.IP 
.IP "\fBPre-Install-Pkgs\fP" 
Esta é uma lista de comandos shell a serem executados antes de se chamar dpkg\&. Como \fBOptions\fP isto deve ser especificado na notação lista\&. Os comandos são chamados em ordem usando /bin/sh; em caso de falhas a execução do APT é cancelada\&.
Apt irá passar aos comandos na entrada padrão os nomes de todos os arquivos \&.deb que ele for instalar, um por linha\&.
.IP 
.IP "\fBRun-Directory\fP" 
APT alterna para este diretório antes de chamar dpkg, o padrão é /\&.
.IP 
.IP "\fBBuild-Options\fP" 
Estas opções são passadas ao dpkg-buildpackage durante a compilação de pacotes, o padrão é desabilitar sinalização e produzir todos os binários\&.
.IP 
.PP 
.SH "Debug - Opções de depuração" 
A maioria das opções na seção \fBdebug\fP não são interessantes ao usuário normal, entretanto, \fBDebug::pkgProblemResolver\fP mostra uma saída interessante sobre as decisões feitas por dist-upgrade\&. \fBDebug::NoLocking\fP desabilita a trava de arquivos de forma que o apt possa executar algumas operações sem ser root e \fBDebug::pkgDPkgPM\fP (ou \fBDebug::pkgRPMPM\fP) irá imprimir a linha de comando para cada chamada de dpkg\&. \fBDebug::IdentCdrom\fP irá desabilitar a inclusão de dados statfs nas IDs de CDROMs\&.
.PP 
.SH "EXEMPLOS" 
\fB/usr/doc/apt/examples/configure-index\&.gz\fP ou
\fB/usr/share/doc/apt*/configure-index\fP 
contém um arquivo exemplo de configurações mostrando os valores padrão de todas as opções possíveis\&.
.PP 
.SH "ARQUIVOS" 
/etc/apt/apt\&.conf
.PP 
.SH "VEJA TAMBÉM" 
apt-cache (8),
apt-get (8)
.PP 
.SH "ERROS" 
Consulte http://bugs\&.debian\&.org/apt\&.  Se você desejar reportar um erro no \fBapt-get\fP, por favor consulte \fB/usr/doc/debian/bug-reporting\&.txt\fP ou o comando \fBbug(1)\fP\&. Se você estiver usando apt em um sistema baseado em RPM, consulte  http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTOR" 
apt-get foi escrito pelo time APT <apt@packages\&.debian\&.org> e portado para sistemas baseados em RPM pela Conectiva S.A. 
<kojima@conectiva\&.com\&.br>\&.


