.TH "vendors\&.list" "5" "25 Out 2000" "apt" "" 
.SH "NOME" 
vendors\&.list \- package vendor list for APT
.PP 
.SH "DESCRIÇÃO" 
A lista do fornecedor do pacote contém uma lista de todos os fornecedores
dos quais você deseja autenticar pacotes que foram baixados. Para cada
fornecedor listado deve conter a impressão de chave GPG correspondente,
para que o apt possa realizar verificação de assinatura do arquivo hash
de índice (hashfile)
e verificação subseqüente da  verificação de cada pacote baixado.
Para ter autenticação habilitada, você deverá adicionar a string de
identificação do fornecedor (veja abaixo) entre colchetes para a
linha \fBsources.list\fP para todos os sites que espelham o repositório
fornecido para aquele fornecedor.
O formato deste arquivo é semelhante ao usado em \fBapt.conf\fP\&.
Constitui-se de um número arbitrário de blocos de fornecedores,
onde cada bloco inicia com uma string informando 
.RI key_type
e o
.RI vendor_id
\&.

.RI key_type
é o tipo de chave do fornecedor a ser definido. Atualmente existe
somente um tipo disponível, o qual é \fBsimple-key\fP\&.

.RI vendor_id
é a string de identificação do fornecedor. É uma string arbitrária que
deve ser fornecida para identificar um fornecedor que está listdo neste
arquivo.

.PP
.SH "simple-key"
Esta chave é composta de dois campos,
\fIFingerprint\fP
e
\fIName\fP
\&. Ambos são obrigatórios\&.


\fIFingerprint\fP
é a impressão de chave-publica gpg(1) para o fornecedor, incluída em
TODAS EM MAIÚSCULAS\&.
A impressão pode ser obtida com a opção --fingerprint da gpg\&.

\fIName\fP
é uma string contendo uma descrição do dono da chave ou fornecedor\&.
Você poderá colocar o nome e email do fornecedor. A string deve estar
destacada com "\&.

.PP
Exemplo:
.nf
single_key "joe"
{
	Fingerprint "0987AB4378FSD872343298787ACC";
	Nome "Joe Shmoe <joe@shmoe.com>";
}
.fi
Para mais informações sobre autenticação de repositório, consultar fontes\&.list(5)\&.

.PP 
.SH "CONSULTE TAMBÉM" 
gpg (1)
sources\&.list (5)
apt-get (8)
.PP 
.SH "BUGS" 
Consultar http://bugs\&.debian\&.org/apt\&. Se você deseja informar sobre um
bug em \fBapt-get\fP, favor consultar \fB/usr/doc/debian/bug-reporting\&.txt\fP
ou o comando\& \fBbug(1)\fP. Se você estiver usando o apt em um sistema baseado em RPM, favor usar http://distro\&.conectiva\&.com\&.br/bugzilla/\&.
.PP 
.SH "AUTOR" 
apt foi escrito pela equipe do APT <apt@packages\&.debian\&.org>
e atualizado para sistemas baseados em RPM pela
Conectiva S.A. <kojima@conectiva\&.com\&.br>

