#!/bin/sh

abort() {
	echo "Abortado."
	exit 1
}

trap abort 2

prerel=0

versao=55
release=1cl

filename=apt-0.3.19cnc$versao

#echo "Atualizando potfiles..."
#(
#cd ~kojima/cvs/i18n/apt
#sudo -u kojima cvs update
#cp *.po ~kojima/rapt/po
#chown kojima.kojima ~kojima/rapt/po/*
#)

today=`LC_ALL= LANG= date '+%a %b %d %Y'`

if [ $release == 1cl -a $prerel == 0 ]; then

if ! grep "released version 0.3.19cnc$versao" apt.spec >/dev/null; then
changelog='*'" $today Alfredo K. Kojima <kojima@conectiva.com.br>\n\
+ apt-0.3.19cnc$versao-$release\n\
- released version 0.3.19cnc$versao\n"
fi

else
changelog=""
fi

WWWDIR=/home/kojima/www/rapt/
export CVS_RSH=ssh

if test `hostname` != minduim; then
	echo "This script is only meant for myself. Don't run it!"
	exit 1
fi

if test $prerel == 1; then
	echo "Gerando PRE versao $versao release $release"
else	
	echo "Gerando versao $versao release $release"
fi

ver=`grep "#define VERSION" configure|sed -e s/"#define VERSION"//`


if test $ver != \"0.3.19cnc$versao\"; then
	echo "Versao do configure está em $ver, atualize para $versao"
	exit 1
fi


echo "Criando tarball a partir do cvs"
(
cd tmp
rm -fr rapt
echo -n CVS
cvs -z3 -d kojima@cvs.conectiva.com.br:/home/cvs export -D now rapt
(cd rapt; make -f Makefile startup; make distclean)
rm -fr $filename
mv rapt $filename
tar czf $filename.tar.gz $filename
cp $filename.tar.gz /usr/src/rpm/SOURCES
)

echo "Gerando apt.spec"

if [ $release == 1cl -a $prerel -eq 0 ]; then
	sed -e s/%changelog/"%changelog\n$changelog"/g apt.spec > tmp.spec
	mv -f tmp.spec apt.spec
fi

sed -e "s/^Version:.*/Version: 0.3.19cnc$versao/" \
	-e "s/^Release:.*/Release: $release/g" apt.spec > tmp.spec
mv -f tmp.spec apt.spec

vim apt.spec -c /changelog


echo "Criando RPM"

rpm -ba apt.spec

if test $prerel == 1; then
	echo "Prerelease pronto!"
	cp /usr/src/rpm/RPMS/i386/$filename-$release* ~kojima/www
	exit
fi

./copy 0.3.19cnc$versao-$release

echo "apt versao $versao, release $release feito!"


echo "Enviar announcement pra lista do apt?"
read res
if test x$res = xy; then

mail apt-rpm@distro.conectiva.com.br -s "[ANNOUNCE] apt 0.3.19cnc$versao-$release" <<END

I've just release apt 0.3.19cnc$versao-$release
You can download it at:

ftp://ftp.conectiva.com/pub/conectiva/EXPERIMENTAL/apt

--
Alfredo
END
echo "Enviado."
fi


